name: CI/CD Workflow

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main
      - "release/**"
      - "hotfix/**"
      - "feature/**"

jobs:
  semantic_version:
    name: Semantic Versioning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"

      - name: Ensure all history is available
        run: |
          if [ -f "$(git rev-parse --git-dir)/shallow" ]; then
            git fetch --unshallow
          fi
          git fetch --all

      - name: Determine semantic version
        id: semantic_version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          major_regexp_flags: ""
          minor_pattern: "(MINOR)"
          minor_regexp_flags: ""
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          change_path: "src/my-service"
          namespace: "my-service"
          bump_each_commit: true
          bump_each_commit_patch_pattern: ""
          search_commit_body: false
          user_format_type: "csv"
          enable_prerelease_mode: true
          debug: false
          version_from_branch: false

      - name: Display version
        run: echo "New version is ${{ steps.semantic_version.outputs.version }}"
